{
  imports = [
    ./bufferline.nix
    ./dashboard.nix
    ./flash.nix
    ./ftplugin.nix
    ./fortune.nix
    ./inc-rename.nix
    ./java.nix
    ./lazygit.nix
    ./lualine.nix
    ./noice.nix
    ./rustaceannvim.nix
    ./tmux-navigator.nix
    ./toggleterm.nix
    ./vim-slime.nix
    ./yanky.nix
  ];
}
